env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - react-app
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  indent:
    - warn
    - 2
    - { "SwitchCase": 1 }
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  no-console: off

