name: 'Generate docs'
description: 'Generate docs for NEAR'
branding:
  icon: book-open
  color: green
inputs:
  source_repo:
    description: 'Source repo to generate docs for'
    required: true
  release_version:
    description: 'Release version'
    required: true
  builder_name:
    description: 'Builder script file'
    required: true
  github_token:
    description: 'GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPOS_OWNER: ${{ github.repository_owner }}
    DOCS_REPO: ${{ github.repository }}
    SOURCE_REPO: ${{ inputs.source_repo }}
    BUILDER_NAME: ${{ inputs.builder_name }}
    SOURCE_TAG: ${{ inputs.release_version }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
